version: "3"

services:
  api:
    image: node:14-alpine
    scale: 2
    working_dir: /app
    networks:
      - default
      - web
    volumes:
      - ./api:/app
    command: sh -c 'yarn && yarn start:dev'

  frontend:
    image: node:14-alpine
    working_dir: /app
    networks:
      - default
      - web
    volumes:
      - ./frontend:/app
    command: sh -c 'yarn && yarn dev'

  postgres:
    image: postgres:12-alpine
    networks:
      - default
      - web
    environment:
      POSTGRES_PASSWORD: postgres

networks:
  web:
    external: true
